sudo: required 
env:
  DOCKER_COMPOSE_VERSION: 1.7.1
install:
  - curl -sSL https://get.docker.com/ | sudo sh
  - curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docer version
  - docker-compose version
  - docker-compose config
  - make build
script:
  - make start
